### PR TITLE
fix symlink lib and fix chmod lib folder

### PR DESCRIPTION
**Pull request by cocka11**

### CODE REVIEW

**Comment by cocka11** [comment]
this fixes the symlink i tested

Të martën, 30 nëntor 2021, Ayan Debnath ***@***.***> shkroi:

**Comment by cocka11** [comment]
> 1. Don't remove **double-quotes** from the for loop.
> 2. What's the reason behind replacing the `$SYS` with `/system`?

I had made 2 mistakes, I fixed them now

**Comment by cocka11** [comment]
The  double quotes  in the for loop are set incorrectly now are fine so
they work

**Comment by ayandebnath** [comment]
> The double quotes in the for loop are set incorrectly now are fine so they work

We also need to check if the gapps is present under `/system` (not only under `/system/product` and `/system/system_ext`)
That's why the blank string (quote) is important.

**Pull request closed without merging**
